name: ShareDine
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ Good job!"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm test